apiVersion: apps/v1
kind: Deployment
metadata:
  name: anil-dep
  namespace: anil
  labels:
    app: dep
    env: prod
    createdBy: anilkumar

spec:
  replicas: 2

  selector:
    matchLabels:
      app: dep

  template:
    metadata:
      labels:
        app: dep

    spec:
      containers:
        - name: maven-nexus-docker-container
          image: anildocker11/maven-nexus-docker:0.0.1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: anil-dep-svc
  namespace: anil
  labels:
    app: dep
    env: prod

spec:
  selector:
    app: dep

  type: NodePort

  ports:
    - port: 8080
      targetPort: 32100
