name: Tom Son Nex Doc EKS

on: workflow_dispatch

jobs:
  Build-Stage:
    runs-on: self-hosted

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup the Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run the Goal
        run: mvn clean package

      - name: Display the war file
        run: ls -l target/

      - name: Upload the Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-war
          path: target/*.war

  
  Kubernetes-EKS-Stage:
    runs-on: self-hosted
    needs: Build-Stage

    steps:
      - name: Check out the Code
        uses: actions/checkout@v4

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name my-k8s-cluster

      - name: Verify the EKS Cluster
        run: |
          kubectl get nodes
          kubectl get ns

      - name: Deployment the Application
        run: |
          kubectl apply -f kubernetes/deployment.yaml

      - name: Status of Deployment Application
        run: |
          kubectl get deployment
          kubectl get svc
          kubectl get po
          kubectl get all


          
