name: Docker-CI

on:
  workflow_dispatch:

jobs:

#=========================================
# BUILD STAGE
#=========================================
  Build-Stage:
    runs-on: self-hosted

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install Maven
        run: |
          sudo apt update -y
          sudo apt install maven -y

      - name: Build Application
        run: mvn clean package

      - name: Display Artifact
        run: ls -lrth target/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-war
          path: target/*.war

#=========================================
# TEST STAGE
#=========================================
  Test-Stage:
    runs-on: self-hosted
    needs: Build-Stage

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Unit Tests
        run: mvn test

      - name: Test Status
        run: echo "Tests Completed Successfully"

#=========================================
# SONARQUBE ANALYSIS
#=========================================
  Sonarqube:
    runs-on: self-hosted
    needs: Test-Stage

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: SonarQube Analysis
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.host.url=http://3.7.68.144:9000 \
            -Dsonar.token=squ_e9f1628cd5a3b03023608531077dc596dde0d6da

