name: Docker-CI

on:
  workflow_dispatch:

jobs:

#=========================================
# BUILD STAGE
#=========================================
  Build-Stage:
    runs-on: self-hosted

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Application
        run: mvn clean package

      - name: Display Artifact
        run: ls -lrth target/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-war
          path: target/*.war

#=========================================
# TEST STAGE
#=========================================
  Test-Stage:
    runs-on: self-hosted
    needs: Build-Stage

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Unit Tests
        run: mvn test

      - name: Test Status
        run: echo "Tests Completed Successfully"

#=========================================
# DOCKER BUILD & PUSH
#=========================================
  Docker-Build:
    runs-on: self-hosted
    needs: Test-Stage

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t anildocker11/maven-web-application:0.0.1 .

      - name: Verify Docker Image
        run: |
          docker images

      - name: Push Docker Image
        run: |
          docker push anildocker11/maven-web-application:0.0.1
